# 1 Import Packages

In [1]:
import xarray as xr
import datetime
import sys
import numpy as np
import pandas as pd

# 2 Create Dummy Data

In [8]:
times = pd.date_range("2000-01-01", "2010-12-31", name="time")

In [14]:
data = xr.DataArray(times.month, dims = ["time"],coords = {"time":times})

In [20]:
times.year.unique().is

Int64Index([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010], dtype='int64', name='time')

In [16]:
def timemean(data, target_timemean, dim = "time"):
    """
    
    
    """
            
    # Calculates the weights if input data is monthly means
    if data.timeaverage == "month":
        
        data_result = (data*weights).groupby(groupby_string).sum(dim=timedim)
    else:
        data_result = data.groupby(groupby_string).sum(dim=timedim) 
    
    
    return data_result    
                                                                            

In [76]:
def calculate_monthly_weights(data, dim, target_timemean):
    """
    
    
    """
    
    groupby_string = ".".join([dim, target_timemean])

    month_length         = data[dim].dt.days_in_month
    month_length_grouped = month_length.groupby(groupby_string)
    weights              = month_length_grouped / month_length_grouped.sum()

    return weights

In [77]:
weights, month_length_grouped = calculate_monthly_weights(data, dim="time",target_timemean="year")

ValueError: too many values to unpack (expected 2)

In [61]:
month_lenght_grouped

<xarray.DataArray 'days_in_month' (year: 11)>
array([11168, 11111, 11111, 11111, 11168, 11111, 11111, 11111, 11168,
       11111, 11111])
Coordinates:
  * year     (year) int64 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010

In [27]:
leap_year = 2016
norm_year = 2015

In [30]:
leap_year_times

DatetimeIndex(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
               '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
               '2016-01-09', '2016-01-10',
               ...
               '2016-12-22', '2016-12-23', '2016-12-24', '2016-12-25',
               '2016-12-26', '2016-12-27', '2016-12-28', '2016-12-29',
               '2016-12-30', '2016-12-31'],
              dtype='datetime64[ns]', name='time', length=366, freq='D')

In [122]:
def test_calculate_monthly_weights():
    leap_year = 2016
    norm_year = 2015
    
    leap_year_times = pd.date_range(str(leap_year)+"-01-01", str(leap_year)+"-12-31", name="time")
    norm_year_times = pd.date_range(str(norm_year)+"-01-01", str(norm_year)+"-12-31", name="time")
    
    leap_year_da = xr.DataArray(leap_year_times, dims=["time"], coords = {"time":leap_year_times})
    norm_year_da = xr.DataArray(norm_year_times, dims=["time"], coords = {"time":norm_year_times})
    
    leap_year_weights = calculate_monthly_weights(leap_year_da, dim="time", target_timemean ="year")
    norm_year_weights = calculate_monthly_weights(norm_year_da, dim="time", target_timemean ="year")
    
    leap_year_weights_calculated = leap_year_times.daysinmonth/np.sum([monthrange(leap_year, x)[1]**2 for x in range(1,13)])
    norm_year_weights_calculated = norm_year_times.daysinmonth/np.sum([monthrange(norm_year, x)[1]**2 for x in range(1,13)])
    
    assert (leap_year_weights_calculated == leap_year_weights).all() 
    assert (norm_year_weights_calculated == norm_year_weights).all()
    
    
    

In [133]:
norm_year_da = xr.DataArray((norm_year_times.month==4)*1, dims=["time"], coords = {"time":norm_year_times})

In [134]:
norm_year_da

<xarray.DataArray (time: 366)>
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
Coordinates:
  * time     (time) datetime64[ns] 2016-01-01 2016-01-02 ... 2016-12-31

In [112]:
assert (leap_year_weights_calculated == leap_year_weights).all() & (norm_year_weights_calculated == norm_year_weights).all()

In [57]:
leap_year_weights.time.dt.daysinmonth

<xarray.DataArray 'days_in_month' (time: 366)>
array([31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
       31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 29, 29, 29,
       29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29,
       29, 29, 29, 29, 29, 29, 29, 29, 29, 31, 31, 31, 31, 31, 31, 31, 31,
       31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
       31, 31, 31, 31, 31, 31, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
       31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 30,
       30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 31, 31, 31, 31, 31,
       31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
       31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
       31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
       31, 31, 31, 31, 31, 31, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
       31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 30,
       30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 31, 31, 31, 31, 31,
       31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
       31, 31, 31, 31, 31, 31, 31, 31, 31])
Coordinates:
  * time     (time) datetime64[ns] 2016-01-01 2016-01-02 ... 2016-12-31
    year     int64 2016

In [ ]:
pd.date_range("2000-01-01", "2010-12-31", name="time")

In [7]:
times.daysinmonth

Int64Index([31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
            ...
            31, 31, 31, 31, 31, 31, 31, 31, 31, 31],
           dtype='int64', name='time', length=731)

In [2]:
times = pd.date_range("2000-01-01", "2001-12-31", name="time")
annual_cycle = np.sin(2 * np.pi * (times.dayofyear.values / 365.25 - 0.28))

base = 10 + 15 * annual_cycle.reshape(-1, 1)
tmin_values = base + 3 * np.random.randn(annual_cycle.size, 3)
tmax_values = base + 10 + 3 * np.random.randn(annual_cycle.size, 3)

ds = xr.Dataset(
    {
        "tmin": (("time", "location"), tmin_values),
        "tmax": (("time", "location"), tmax_values),
    },
    {"time": times, "location": ["IA", "IN", "IL"]},
)

ds

<xarray.Dataset>
Dimensions:   (location: 3, time: 731)
Coordinates:
  * time      (time) datetime64[ns] 2000-01-01 2000-01-02 ... 2001-12-31
  * location  (location) <U2 'IA' 'IN' 'IL'
Data variables:
    tmin      (time, location) float64 0.2006 -3.569 -1.084 ... 0.3216 -2.376
    tmax      (time, location) float64 9.127 2.808 10.53 ... 6.87 3.217 4.782

In [3]:
times.dayofyear

Int64Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
            ...
            356, 357, 358, 359, 360, 361, 362, 363, 364, 365],
           dtype='int64', name='time', length=731)